name: Docker Setup Test

on:
  push:

jobs:
  docker-info:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - name: Update apt and install dependencies
        run: |
          apt-get update
          apt-get install -y \
            curl \
            gnupg \
            lsb-release \
            ca-certificates

      - name: Add Docker repository and install Docker CLI + Compose
        run: |
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          apt-get update
          apt-get install -y docker-ce-cli docker-compose-plugin

      - name: Dump package config
        run: cat /etc/apt/sources.list.d/docker.list
      - name: Show Docker CLI version
        run: docker --version

      - name: Show Docker Compose version
        run: docker compose version
